---
title: "Geospatial R Part II"
output: html_document
---
```{r Init, message=FALSE, results="hide"}
library(rgdal)
#library(rgeos)
#library(maptools)
library(ggplot2)
#library(png)
```
#Demo I: Natural Earth Continent Data
##Load and Inspect Continent Data
```{r LoadContinentData, message=FALSE, results="hide"}
cont.str <- "ne_110m_land"
cont.df <- readOGR(cont.str, cont.str)
```
```{r InspectContinentData}
str(cont.df, max.level=2)
str(cont.df@data, max.level=1)
cont.df@polygons[1]
cont.df@plotOrder
cont.df@bbox
cont.df@proj4string
```
##Plot Continent Data As-is
```{r PlotContinentsLatLong}
fcont.df <- fortify(cont.df)
ggplot(fcont.df, aes(long, lat, group=group)) +
    geom_polygon() +
    coord_fixed()
```
##Transform and Plot Continent Data
```{r PlotContinentsRobinson}
rob.proj <- CRS("+proj=robin")
rob.cont.df <- spTransform(cont.df, rob.proj)
frob.cont.df <- fortify(rob.cont.df)
cont.plot <- ggplot(frob.cont.df, aes(long, lat, group=group)) +
    geom_polygon() +
    coord_fixed()
cont.plot
```
```{r IncludeBBox}
bbox.str <- "ne_110m_wgs84_bounding_box"
bbox.df <- readOGR(bbox.str, bbox.str)
rob.bbox.df <- spTransform(bbox.df, rob.proj)
frob.bbox.df <- fortify(rob.bbox.df)
cont.plot <- ggplot(data=frob.bbox.df, aes(long, lat)) +
    geom_polygon(fill="blue") +
    geom_polygon(data=frob.cont.df, aes(long, lat, group=group), fill="black") 
cont.plot
#spTransform(
#readOGR(paste(cont.dir, bbox.data, sep = "/"), bbox.data), CRS(fig.CRS)))
#fcont.df <<- fortify(spTransform(readOGR(paste(cont.dir, cont.data, sep = "/"), cont.data), CRS(fig.CRS)))
#flake.df <<- fortify(spTransform(readOGR(paste(lake.dir, lake.data, sep = "/"), lake.data), CRS(fig.CRS)))
```